// Copyright (c) 2025 Perfect Aduh. MIT License. See LICENSE for details.

import Foundation

/// Represents the role of a message sender in the AG-UI protocol.
///
/// Roles are used to identify the source of messages in conversations between
/// developers, systems, AI assistants, users, tools, and activities.
///
/// The role field serves as the discriminator for polymorphic message types,
/// allowing the protocol to deserialize messages into their specific concrete types.
///
/// - SeeAlso: ``Message``
public enum Role: String, Sendable, Codable, CaseIterable, Hashable {
    /// Developer-level instructions and configuration messages.
    ///
    /// Developer messages typically contain system-level instructions that configure
    /// or control the agent's behavior at a foundational level.
    case developer

    /// System instructions and behavioral guidelines for the agent.
    ///
    /// System messages provide high-level instructions that guide the agent's
    /// behavior, personality, and response patterns.
    case system

    /// Messages generated by the AI assistant.
    ///
    /// Assistant messages represent responses from the AI agent, which may include
    /// text content and/or tool calls requesting to execute functions.
    case assistant

    /// Messages from the human user.
    ///
    /// User messages contain human input, supporting both simple text content
    /// and multimodal content (text, images, binary data).
    case user

    /// Results from tool execution.
    ///
    /// Tool messages contain the results of function executions that were
    /// requested by the assistant through tool calls.
    case tool

    /// Streaming structured content for UI surfaces.
    ///
    /// Activity messages enable agents to stream structured JSON content
    /// that can be rendered in custom UI surfaces.
    case activity

    /// Internal reasoning content produced by the agent.
    ///
    /// Reasoning messages contain the agent's chain-of-thought or internal
    /// reasoning steps. They may optionally carry an encrypted value for
    /// verified reasoning workflows.
    case reasoning
}
