/*
 * MIT License
 *
 * Copyright (c) 2025 Perfect Aduh
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import Foundation

/// Represents the role of a message sender in the AG-UI protocol.
///
/// Roles are used to identify the source of messages in conversations between
/// developers, systems, AI assistants, users, tools, and activities.
///
/// The role field serves as the discriminator for polymorphic message types,
/// allowing the protocol to deserialize messages into their specific concrete types.
///
/// - SeeAlso: ``Message``
public enum Role: String, Sendable, Codable, CaseIterable, Hashable {
    /// Developer-level instructions and configuration messages.
    ///
    /// Developer messages typically contain system-level instructions that configure
    /// or control the agent's behavior at a foundational level.
    case developer

    /// System instructions and behavioral guidelines for the agent.
    ///
    /// System messages provide high-level instructions that guide the agent's
    /// behavior, personality, and response patterns.
    case system

    /// Messages generated by the AI assistant.
    ///
    /// Assistant messages represent responses from the AI agent, which may include
    /// text content and/or tool calls requesting to execute functions.
    case assistant

    /// Messages from the human user.
    ///
    /// User messages contain human input, supporting both simple text content
    /// and multimodal content (text, images, binary data).
    case user

    /// Results from tool execution.
    ///
    /// Tool messages contain the results of function executions that were
    /// requested by the assistant through tool calls.
    case tool

    /// Streaming structured content for UI surfaces.
    ///
    /// Activity messages enable agents to stream structured JSON content
    /// that can be rendered in custom UI surfaces.
    case activity
}
